@apiV1 = http://localhost:3000/api/v1/users

PATCH  {{apiV1}}/1 HTTP/1.1

{
    "email": "admin@sing.com",
    "fullName": "sing",
    "password": "123456"
}

###
DELETE  {{apiV1}}/4
Content-Type: application/json