version: '3.9'
services:

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
      - MYSQL_DATABASE=nestjs
    volumes:
      - "./data:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080